name: flutter_tinder_learn
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # http: ^0.13.4
  # shared_preferences: ^2.0.5
  # wave: ^0.2.0
  # fluttertoast: ^8.0.3
  # flutter_easyloading: ^3.0.0
  # flutter_svg: ^0.21.0+1
  # flutter_staggered_grid_view: ^0.4.0
  # cached_network_image: ^3.0.0
  # get: 4.3.8
  # firebase_auth: ^3.1.3
  # google_sign_in: ^5.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: '^1.7.0'
  firebase_auth: '^3.1.3'
  firebase_database: '^8.0.0'
  get: ^4.3.8

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/girls/
  uses-material-design: true
