name: flutter_tinder_learn
version: 2.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  firebase_core: '^1.7.0'
  firebase_auth: '^3.1.3'
  google_sign_in: ^5.2.1
  cloud_firestore: ^2.5.4
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_icons:
  image_path: 'assets/images/instantLearn.png'
  android: true
  # ios: true
